config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :dishes
  resources :relationships, only: [:create, :destroy]
  get :favorites,     to: 'favorites#index'
  post   "favorites/:dish_id/create"  => "favorites#create"
  delete "favorites/:dish_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  get :lists, to: 'lists#index'
  post   "lists/:dish_id/create"  => "lists#create"
  delete "lists/:list_id/destroy" => "lists#destroy"
  resources :logs, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 5)
      @log = Log.new
    end
  end

  def about
  end

  def terms
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "クック-ウィズとは？") %>
<div id="fh5co-about" class="about-page">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h1 class="about-title">クック-ウィズとは？</h1>
      </div>
      <br>
      <div class="col-md-8 col-md-offset-2">
        <h3 class="about-service">料理を投稿して共有できるサービスです。</h3>
        <br>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <h2 class="about-main">主な使い方</h2>
      </div>
        <div class="col-md-8 col-md-offset-2">
          <div class="about-explanation">
            <ul>
              <li>料理の投稿</li>
              <p class="main-description"><span>メモ</span>や<span>写真</span>とともに料理の投稿をすることができます。<br>
              また、その料理を何回作った事があるのか、<span>記録</span>を残すことが出来ます。
              </p>
              <li>他のユーザーとの共有</li>
              <p class="main-description"><span>フォロー機能</span>がついており、他のユーザーをフォロー出来ます。<br>
              またそのユーザーの料理に対して、<span>コメント、お気に入り、作る予定リスト</span>へ登録することなどが出来ます。</p>
              <li>検索機能</li>
              <p>材料や料理名を元に<span>検索</span>することが出来ます。</p>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div id="fh5co-portfolio">
    <div class="container">
      <div class="col-md-9">
        <h3>みんなの料理 (<%= @feed_items.count %>)</h3>
        <%= render 'shared/feed' %>
      </div>
      <div class="col-md-3">
        <p><%= link_to "新しい料理を作る", new_dish_path, class: "btn btn-primary btn-lg btn-demo btn-record" %></p>
        <br>
        <p><%= link_to "みんなの料理をCSV出力", dishes_path(format: :csv), class: "btn btn-primary btn-lg btn-demo btn-csv" %></p>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'shared/recruit_login' %>
  <header id="fh5co-header" class="fh5co-cover js-fullheight" role="banner">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
          <div class="display-t js-fullheight">
            <div class="display-tc js-fullheight animate-box" data-animate-effect="fadeIn">
              <h1>　料理を投稿して、<br>
            みんなと共有しませんか？</h1>
              <h2>料理の輪を広めよう！！</h2>
              <p>
                <%= link_to 'クック-ウィズを始める', signup_path, class: "btn btn-primary btn-lg btn-demo" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
<% end %>

app/views/static_pages/terms.html.erb
<% provide(:title, "利用規約") %>
<div id="fh5co-about">
  <div class="container">
    <h1>利用規約</h1>
  </div>
</div>